[general]
cpus = 16
editor = "nano"
doas = false
language = "en-US"
noconfirm = false

[aur]
build = "/home/stereomato/.cache/aura/builds"
cache = "/home/stereomato/.cache/aura/cache"
clones = "/home/stereomato/.cache/aura/packages"
hashes = "/home/stereomato/.cache/aura/hashes"
chroot = []
ignores = []
git = false
hotedit = true
shellcheck = true
diff = true
delmakedeps = false
clean = true
warn_unknowns = true
nocheck = false
skipdepcheck = false
reverse = false

[backups]
snapshots = "/home/stereomato/.cache/aura/snapshots"
automatic = true

